service: weather-app-microservice

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  
package:
  artifact: target/weather-app-microservice.jar

functions:
  currentWeather:
    handler: com.serverless.Handler
    events:
      - http:
          path: weather/city
          method: get
          cors: true
          integration: lambda
          request:
            template:
              application/json: >
                {
                  "id" : "$input.params('id')"
                }
          environment:
              WEATHER_API_BASE_URL: http://api.openweathermap.org/data/2.5/weather?&APPID=0c87cd4372ac1f3b58570b17e8f7326b&units=metric