service: weather-app-microservice

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  
package:
  artifact: target/weather-app-microservice.jar

functions:
  currentWeather:
    handler: com.serverless.Handler
    events:
      - http:
          path: weather/city
          method: get
          integration: lambda
          request:
            template:
              application/json: >
                {
                  "cityId" : "$input.params('Id')"
                }
